/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        welcome: [];
        register: [];
        'register.store': [];
        login: [];
        'login.store': [];
        'profile.show': [];
        'admin.login': [];
        'admin.login.store': [];
        'admin.logout': [];
        'admin.dashboard': [];
        'admin.admins.index': [];
        'admin.admins.store': [];
        'admin.admins.update': [
            {
                name: 'admin';
                required: true;
                binding: 'id';
            },
        ];
        'admin.users.index': [];
        'admin.users.show': [
            {
                name: 'user';
                required: true;
                binding: 'id';
            },
        ];
        'admin.companies.index': [];
        'admin.workspaces.index': [];
        'admin.workspaces.show': [
            {
                name: 'workspace';
                required: true;
            },
        ];
        'admin.boards.index': [];
        'admin.boards.show': [
            {
                name: 'board';
                required: true;
            },
        ];
        'admin.cards.index': [];
        'admin.roles.index': [];
        'admin.roles.store': [];
        'admin.roles.permissions.edit': [
            {
                name: 'adminRole';
                required: true;
                binding: 'id';
            },
        ];
        'admin.roles.permissions.update': [
            {
                name: 'adminRole';
                required: true;
                binding: 'id';
            },
        ];
        logout: [];
        'company.setup': [];
        'company.setup.store': [];
        dashboard: [];
        'companies.index': [];
        'users.index': [];
        'workspaces.index': [];
        'boards.index': [];
        'cards.index': [];
        'roles.index': [];
        'roles.store': [];
        'roles.permissions.edit': [
            {
                name: 'role';
                required: true;
                binding: 'id';
            },
        ];
        'roles.permissions.update': [
            {
                name: 'role';
                required: true;
                binding: 'id';
            },
        ];
        'password.request': [];
        'password.email': [];
        'password.reset': [
            {
                name: 'token';
                required: true;
            },
        ];
        'password.update': [];
        'verification.notice': [];
        'verification.verify': [
            {
                name: 'id';
                required: true;
            },
            {
                name: 'hash';
                required: true;
            },
        ];
        'verification.send': [];
        'password.confirm': [];
        'password.confirmation': [];
        'password.confirm.store': [];
        'two-factor.login': [];
        'two-factor.login.store': [];
        'two-factor.enable': [];
        'two-factor.confirm': [];
        'two-factor.disable': [];
        'two-factor.qr-code': [];
        'two-factor.secret-key': [];
        'two-factor.recovery-codes': [];
        'two-factor.regenerate-recovery-codes': [];
        'passkey.login-options': [];
        'passkey.login': [];
        'passkey.confirm-options': [];
        'passkey.confirm': [];
        'passkey.registration-options': [];
        'passkey.store': [];
        'passkey.destroy': [
            {
                name: 'passkey';
                required: true;
                binding: 'id';
            },
        ];
        'profile.edit': [];
        'profile.update': [];
        'company.profile.update': [];
        'profile.destroy': [];
        'security.edit': [];
        'user-password.update': [];
        'appearance.edit': [];
        'well-known.passkeys': [];
        'storage.local': [
            {
                name: 'path';
                required: true;
            },
        ];
        'storage.local.upload': [
            {
                name: 'path';
                required: true;
            },
        ];
    }
}
export {};
